Repository NotEnoughUpdates/NotEnoughUpdates, pull requests merged in 2022-10, with the labels that each got.

#373 Disable neu hax when not in skyblock
  src/main/java/io/github/moulberry/notenoughupdates/listener/ChatListener.java
Labels: bug-fix

#366 Fix pv crash when in f7
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
Labels: bug-fix

#360 Fixed buggy cape in /pv
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/BasicPage.java
Labels: bug-fix

#377 Couple minor bug fixes
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/DamageCommas.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ProfileViewer.java
  src/main/java/io/github/moulberry/notenoughupdates/util/ItemUtils.java
Labels: bug-fix

#351 Update DevTestCommand developer check
  src/main/java/io/github/moulberry/notenoughupdates/commands/dev/DevTestCommand.java
Labels: bug-fix

#356 Fixed /join not always going to Master Mode
  src/main/java/io/github/moulberry/notenoughupdates/commands/dungeon/JoinDungeonCommand.java
Labels: bug-fix

#371 Fix crash when a list config option doesnt have that many options (generally from downgrading)
  src/main/java/io/github/moulberry/notenoughupdates/core/config/gui/GuiOptionEditorDraggableList.java
Labels: bug-fix

#361 Remove the extra bar textures as fsr never used them
  src/main/java/io/github/moulberry/notenoughupdates/core/GuiElementBoolean.java
  src/main/java/io/github/moulberry/notenoughupdates/util/GuiTextures.java
  src/main/resources/assets/notenoughupdates/core/bar_1.png
  src/main/resources/assets/notenoughupdates/core/bar_2.png
  src/main/resources/assets/notenoughupdates/core/bar_3.png
  src/main/resources/assets/notenoughupdates/core/bar_on.png
Labels: bug-fix

#355 Will now actually set up the pickaxe cooldown on first world joined
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/ItemCooldowns.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/MiningOverlay.java
Labels: bug-fix

#379 reclaim neutrality
  .github/CODE_OF_CONDUCT.md
Labels: documentation

#381 contributing
  CONTRIBUTING.md
Labels: documentation

#380 Added optifine to /neustats
  src/main/java/io/github/moulberry/notenoughupdates/commands/dev/StatsCommand.java
Labels: feature

#339 Miscellaneous Typos
  src/main/java/io/github/moulberry/notenoughupdates/commands/dev/DevTestCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/commands/dev/StatsCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/commands/help/HelpCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/commands/misc/AhCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/commands/misc/CosmeticsCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/commands/misc/CustomizeCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/commands/misc/UpdateCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/commands/profile/PeekCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/commands/profile/ViewProfileCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/CalendarOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/AHTweaks.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/ApiData.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Calendar.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Dungeons.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/ImprovedSBMenu.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/LocationEdit.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Misc.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/TradeMenu.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/MiningOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/BasicPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
  src/main/resources/mcmod.info
Labels: bug-fix

#369 If above 100% of price will show actual added percentage
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/AuctionBINWarning.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/AHTweaks.java
Labels: bug-fix

#352 added fishing ding for main lobby lava fishing
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/FishingHelper.java
Labels: feature

#359 Made it so the user could customize how long the mod waits before pau…
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/SkillOverlays.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/CombatSkillOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/FarmingSkillOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/FishingSkillOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/MiningSkillOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/OverlayManager.java
Labels: feature

#374 [Calculator] Add exponent operator and % postfix
  src/main/java/io/github/moulberry/notenoughupdates/util/Calculator.java
Labels: feature

#385 NEU/NEU vs Moulberry/NEU Contributor note
  CONTRIBUTING.md
Labels: documentation

#338 Trophy Fish Total Count
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/trophy/TrophyFishPage.java
Labels: feature

#358 Ctrl + Z and (Ctrl + Y and Ctrl + Shift + Z) support
  src/main/java/io/github/moulberry/notenoughupdates/NEUOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinGuiTextField.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Misc.java
  src/main/resources/mixins.notenoughupdates.json
Labels: feature

#322 Remove messages in chat if they are under a set skyblock level
  Update Notes/2.1.1.md
  src/main/java/io/github/moulberry/notenoughupdates/listener/ChatListener.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Misc.java
Labels: feature

#363 Entity Scale and Party and Guild chat social options
  src/main/java/io/github/moulberry/notenoughupdates/listener/ChatListener.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/entityviewer/EntityViewer.java
  src/main/java/io/github/moulberry/notenoughupdates/util/Utils.java
Labels: feature

#370 Faction Town Board Quests added to Todo Overlay
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/MiscOverlays.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/OverlayManager.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/TimersOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/util/SBInfo.java
Labels: feature

#350 Me when I read NEU code
  src/main/java/io/github/moulberry/notenoughupdates/listener/RenderListener.java
Labels: bug-fix

#303 Soopy networth option in pv
  src/main/java/io/github/moulberry/notenoughupdates/commands/profile/PeekCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/ProfileViewer.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/BasicPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ProfileViewer.java
  src/main/java/io/github/moulberry/notenoughupdates/util/ApiUtil.java
Labels: feature

#314 misc pv changes
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/BasicPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ExtraPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/weight/weight/DungeonsWeight.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/weight/weight/SkillsWeight.java
Labels: feature

#311 AND | OR support for container search.
  src/main/java/io/github/moulberry/notenoughupdates/NEUManager.java
Labels: feature

#376 Made cool kill/death stuff in profile viewer
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ExtraPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
Labels: feature

#263 Added Powder Grinding Tracker
  src/main/java/io/github/moulberry/notenoughupdates/NotEnoughUpdates.java
  src/main/java/io/github/moulberry/notenoughupdates/listener/ChatListener.java
  src/main/java/io/github/moulberry/notenoughupdates/listener/WorldListener.java
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/LocationEdit.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Mining.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/OverlayManager.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/PowderGrindingOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/util/SBInfo.java
Labels: feature

#387 Fix fish related crash
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/trophy/TrophyFishPage.java
Labels: bug-fix

#309 Added the ability to add search tags to config options
  src/main/java/io/github/moulberry/notenoughupdates/NEUManager.java
  src/main/java/io/github/moulberry/notenoughupdates/commands/misc/UpdateCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/core/config/annotations/ConfigOption.java
  src/main/java/io/github/moulberry/notenoughupdates/core/config/struct/ConfigProcessor.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/DamageCommas.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/InventoryStorageSelector.java
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfigEditor.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/AHGraph.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/ApiData.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Calendar.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/CustomArmour.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/DungeonMapConfig.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Dungeons.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Enchanting.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Fishing.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/ItemOverlays.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Itemlist.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/LocationEdit.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Mining.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Misc.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/MiscOverlays.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/PetOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/SkillOverlays.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/StorageGUI.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/TooltipTweaks.java
Labels: feature

#302 Buttons tooltip delay
  src/main/java/io/github/moulberry/notenoughupdates/listener/RenderListener.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/InventoryButtons.java
Labels: feature

#391 Fix calculator crash by using correct apis
  src/main/java/io/github/moulberry/notenoughupdates/util/Calculator.java
Labels: bug-fix

#393 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#333 Code Cleanup
  src/main/java/io/github/moulberry/notenoughupdates/auction/CustomAH.java
  src/main/java/io/github/moulberry/notenoughupdates/commands/Commands.java
  src/main/java/io/github/moulberry/notenoughupdates/commands/misc/ButtonsCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/commands/misc/CustomizeCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/dungeons/DungeonMap.java
  src/main/java/io/github/moulberry/notenoughupdates/dungeons/GuiDungeonMapEditor.java
  src/main/java/io/github/moulberry/notenoughupdates/infopanes/DevInfoPane.java
  src/main/java/io/github/moulberry/notenoughupdates/itemeditor/GuiElementTextField.java
  src/main/java/io/github/moulberry/notenoughupdates/listener/ChatListener.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/tutorials/NeuConfigTutorial.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/tutorials/NeuTutorial.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/tutorials/TutorialBase.java
  src/main/java/io/github/moulberry/notenoughupdates/util/Utils.java
Labels: bug-fix

#310 neuec tooltip cache
  src/main/java/io/github/moulberry/notenoughupdates/listener/ItemTooltipListener.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/ItemCustomizeManager.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Misc.java
Labels: bug-fix

#397 Config :skull:
  src/main/java/io/github/moulberry/notenoughupdates/listener/ItemTooltipListener.java
Labels: bug-fix

#402 Fixed Magma Boss Bestiary
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/bestiary/BestiaryData.java
Labels: bug-fix

#400 Migrate away from set-output
  .github/workflows/send_webhook_update.sh
Labels: bug-fix

#394 no more infinite scroll
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ExtraPage.java
Labels: bug-fix

#403 Add networth leaderboard position to hover lore
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/BasicPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ProfileViewer.java
Labels: feature

#395 Endermite Nests Alert + TitleUtil
  src/main/java/io/github/moulberry/notenoughupdates/NotEnoughUpdates.java
  src/main/java/io/github/moulberry/notenoughupdates/listener/ChatListener.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/EnderNodes.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Notifications.java
  src/main/java/io/github/moulberry/notenoughupdates/util/TitleUtil.java
Labels: feature

#368 Croesus profit overlay
  src/main/java/io/github/moulberry/notenoughupdates/NEUOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/NotEnoughUpdates.java
  src/main/java/io/github/moulberry/notenoughupdates/auction/APIManager.java
  src/main/java/io/github/moulberry/notenoughupdates/listener/ItemTooltipRngListener.java
  src/main/java/io/github/moulberry/notenoughupdates/listener/RenderListener.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/DungeonNpcProfitOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinGuiContainer.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Dungeons.java
Labels: feature

#357 Recipe History and Fairy Soul distance meter.
  Update Notes/2.1.1.md
  src/main/java/io/github/moulberry/notenoughupdates/NEUManager.java
  src/main/java/io/github/moulberry/notenoughupdates/core/util/render/RenderUtils.java
  src/main/java/io/github/moulberry/notenoughupdates/listener/NEUEventListener.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/FairySouls.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/GuiItemRecipe.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Misc.java
  src/main/java/io/github/moulberry/notenoughupdates/recipes/RecipeHistory.java
Labels: feature

#349 Support for cata 50+ and class average.
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/DungeonPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
Labels: feature

#404 Add label to unmerged PRs
  .github/workflows/infer.yml
  .github/workflows/remove-merge-needed-label.yml
Labels: documentation

#399 Added the ability for abicases to work
  src/main/java/io/github/moulberry/notenoughupdates/NEUManager.java
  src/main/java/io/github/moulberry/notenoughupdates/util/ItemResolutionQuery.java
Labels: bug-fix, feature

#398 Fix picknimbus not working for ability cooldown
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/ItemCooldowns.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinGuiTextField.java
Labels: bug-fix
