Repository NotEnoughUpdates/NotEnoughUpdates, pull requests merged in 2022-11, with the labels that each got.

#412 Prevents wrong coopadd commands
  src/main/java/io/github/moulberry/notenoughupdates/NotEnoughUpdates.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/AntiCoopAdd.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinNetHandlerPlayClient.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Misc.java
Labels: feature

#414 added support for commas to /neucalc
  src/main/java/io/github/moulberry/notenoughupdates/util/Calculator.java
Labels: bug-fix

#313 Essenceupgrades gui
  src/main/java/io/github/moulberry/notenoughupdates/ItemPriceInformation.java
  src/main/java/io/github/moulberry/notenoughupdates/core/util/StringUtils.java
  src/main/java/io/github/moulberry/notenoughupdates/listener/RenderListener.java
  src/main/java/io/github/moulberry/notenoughupdates/recipes/EssenceUpgrades.java
  src/main/java/io/github/moulberry/notenoughupdates/recipes/RecipeType.java
  src/main/java/io/github/moulberry/notenoughupdates/util/Constants.java
  src/main/java/io/github/moulberry/notenoughupdates/util/ItemUtils.java
  src/main/resources/assets/notenoughupdates/textures/gui/essence_upgrades_tall.png
Labels: feature

#416 [Fix] Chat Listener index out of bounds
  src/main/java/io/github/moulberry/notenoughupdates/listener/ChatListener.java
Labels: bug-fix

#375 Custom Wither Cloak
  src/main/java/io/github/moulberry/notenoughupdates/NotEnoughUpdates.java
  src/main/java/io/github/moulberry/notenoughupdates/core/util/render/RenderUtils.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/WitherCloakChanger.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinEntityChargedCreeper.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/ItemOverlays.java
  src/main/resources/assets/notenoughupdates/wither_cloak_shield.png
  src/main/resources/mixins.notenoughupdates.json
Labels: feature

#409 Added the extra MP that abicases give to pv
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/InventoriesPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/PlayerStats.java
Labels: feature

#346 Crimson Isle Profile Viewer Page
  Update Notes/2.1.1.md
  src/main/java/io/github/moulberry/notenoughupdates/NotEnoughUpdates.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/ProfileViewer.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/CrimsonIslePage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
  src/main/resources/assets/notenoughupdates/pv_crimson_isle_page.png
Labels: feature

#316 Gui editor
  src/main/java/io/github/moulberry/notenoughupdates/commands/dungeon/MapCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/core/config/Position.java
  src/main/java/io/github/moulberry/notenoughupdates/core/config/gui/GuiPositionEditor.java
  src/main/java/io/github/moulberry/notenoughupdates/core/config/gui/GuiPositionEditorButForTheDungeonMap.java
  src/main/java/io/github/moulberry/notenoughupdates/dungeons/DungeonMap.java
  src/main/java/io/github/moulberry/notenoughupdates/dungeons/GuiDungeonMapEditor.java
  src/main/java/io/github/moulberry/notenoughupdates/listener/RenderListener.java
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Dungeons.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/ItemOverlays.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/LocationEdit.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Mining.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/MiscOverlays.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/PetOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/SkillOverlays.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/SlayerOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/FuelBar.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/FuelBarDummy.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/MapDummy.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/OverlayManager.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/TextOverlay.java
Labels: feature

#419 Fixed the biggest bug in neu history
  src/main/java/io/github/moulberry/notenoughupdates/recipes/EssenceUpgrades.java
Labels: bug-fix

#422 Fixes social controls in party and guild chats
  src/main/java/io/github/moulberry/notenoughupdates/util/Utils.java
Labels: bug-fix

#420 Removed prerelease option, set prerelease branch as default
  src/main/java/io/github/moulberry/notenoughupdates/NEUManager.java
  src/main/java/io/github/moulberry/notenoughupdates/NotEnoughUpdates.java
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/ApiData.java
Labels: feature

#427 Fix race condition in graph
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/GuiPriceGraph.java
Labels: bug-fix

#415 Abiphone favourites
  Update Notes/2.1.1.md
  src/main/java/io/github/moulberry/notenoughupdates/NotEnoughUpdates.java
  src/main/java/io/github/moulberry/notenoughupdates/core/util/render/RenderUtils.java
  src/main/java/io/github/moulberry/notenoughupdates/events/ReplaceItemEvent.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/AbiphoneFavourites.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinGuiContainer.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinInventoryBasic.java
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Misc.java
  src/main/resources/mixins.notenoughupdates.json
Labels: feature

#431 fix npe in the chat thingy
  src/main/java/io/github/moulberry/notenoughupdates/listener/ChatListener.java
Labels: bug-fix

#434 Removed Abicase from Dev Pane and added missing update note
  Update Notes/2.1.1.md
  src/main/java/io/github/moulberry/notenoughupdates/infopanes/DevInfoPane.java
Labels: documentation, feature

#433 Fix god pot
  src/main/java/io/github/moulberry/notenoughupdates/overlays/TimersOverlay.java
Labels: bug-fix

#423 ctrl +f support
  Update Notes/2.1.1.md
  src/main/java/io/github/moulberry/notenoughupdates/NEUOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/infopanes/DevInfoPane.java
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfigEditor.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Toolbar.java
Labels: feature

#437 Show slayer overlay in "None" location
  src/main/java/io/github/moulberry/notenoughupdates/overlays/SlayerOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/util/SBInfo.java
Labels: bug-fix, feature

#439 Aatrox buff calculation in Slayer Overlay
  Update Notes/2.1.1.md
  src/main/java/io/github/moulberry/notenoughupdates/overlays/SlayerOverlay.java
Labels: feature

#442 Star Cult Timer
  Update Notes/2.1.1.md
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Mining.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/MiningOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/util/StarCultCalculator.java
Labels: feature

#436 Added Senither Weight Leaderboard Position
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/BasicPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ProfileViewer.java
Labels: feature

#443 Fixed bugs & added sb xp to minion helper
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/DungeonNpcProfitOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/minionhelper/Minion.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/minionhelper/MinionHelperManager.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/minionhelper/loaders/repo/MinionHelperRepoLoader.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/minionhelper/render/MinionHelperOverlay.java
Labels: bug-fix

#365 Added repo parserer for the draconic table thingy
  src/main/java/io/github/moulberry/notenoughupdates/listener/ItemTooltipListener.java
  src/main/java/io/github/moulberry/notenoughupdates/listener/RenderListener.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/dev/RepoExporters.java
  src/main/java/io/github/moulberry/notenoughupdates/util/ItemUtils.java
Labels: feature

#411 Added Abiphone contact requirements and location.
  Update Notes/2.1.1.md
  src/main/java/io/github/moulberry/notenoughupdates/NotEnoughUpdates.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/AbiphoneContactHelper.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/Navigation.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/GuiNavigation.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/TooltipTweaks.java
  src/main/java/io/github/moulberry/notenoughupdates/util/Constants.java
Labels: feature

#435 Terrible Kotlin!
  build.gradle.kts
  buildSrc/src/main/kotlin/neubs/versioning.kt
  src/main/java/io/github/moulberry/notenoughupdates/commands/dev/DevTestCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/envcheck/EnvironmentScan.java
  src/main/java/io/github/moulberry/notenoughupdates/loader/KotlinLoadingTweaker.java
  src/main/java/io/github/moulberry/notenoughupdates/loader/ModLoadingTweaker.java
  src/main/java/io/github/moulberry/notenoughupdates/loader/NEUDelegatingTweaker.java
Labels: bug-fix

#445 fix star cult
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Mining.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/MiningOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/util/StarCultCalculator.java
Labels: bug-fix

#440 show price of essence when pressing shift in essence upgrades gui
  src/main/java/io/github/moulberry/notenoughupdates/ItemPriceInformation.java
  src/main/java/io/github/moulberry/notenoughupdates/recipes/EssenceUpgrades.java
Labels: bug-fix

#432 Fix todo overlay
  Update Notes/2.1.1.md
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/CookieWarning.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/TimersOverlay.java
Labels: bug-fix

#406 EnchantStyleCustomizer rewrite
  build.gradle.kts
  src/main/java/io/github/moulberry/notenoughupdates/NotEnoughUpdates.java
  src/main/java/io/github/moulberry/notenoughupdates/listener/ItemTooltipListener.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/item/enchants/EnchantMatcher.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/item/enchants/EnchantStyleCustomizer.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Misc.java
  src/main/java/io/github/moulberry/notenoughupdates/util/LRUCache.java
  src/main/java/io/github/moulberry/notenoughupdates/util/LateBindingChroma.java
  src/main/java/io/github/moulberry/notenoughupdates/util/Utils.java
Labels: bug-fix

#450 Update SlayerOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/SlayerOverlay.java
Labels: bug-fix

#448 Added Overlaystyle option to powder grinding tracker
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Mining.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/OverlayManager.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/MiningPage.java
Labels: bug-fix, feature
