Repository NotEnoughUpdates/NotEnoughUpdates, pull requests merged in 2023-01, with the labels that each got.

#529 Meet Your New Dungeon Group Members in Seconds!
  src/main/java/io/github/moulberry/notenoughupdates/listener/ChatListener.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Misc.java
Labels: feature

#494 Hotkeys for wardrobe slots
  src/main/java/io/github/moulberry/notenoughupdates/NotEnoughUpdates.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/WardrobeMouseButtons.kt
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/WardrobeKeybinds.java
  src/main/java/io/github/moulberry/notenoughupdates/util/Utils.java
Labels: feature

#537 Fix skin downloads on some older java versions
  src/main/java/io/github/moulberry/notenoughupdates/hooks/ThreadDownloadImageHook.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinThreadDownloadImageData.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinThreadDownloadImageDataThread.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Misc.java
  src/main/java/io/github/moulberry/notenoughupdates/util/ApiUtil.java
  src/main/resources/mixins.notenoughupdates.json
  src/main/resources/neukeystore.jks
  src/main/resources/neukeystore.txt
Labels: bug-fix

#531 Bonzo Mask Durability Cooldown
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/ItemCooldowns.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/ItemOverlays.java
Labels: feature

#547 Changed Fishing Timer from 30 to 20 seconds
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/FishingHelper.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Fishing.java
Labels: bug-fix

#534 PetLeveling: Allow for defining custom level offsets for pets
  src/main/kotlin/io/github/moulberry/notenoughupdates/util/PetLeveling.kt
  src/test/kotlin/io/github/moulberry/notenoughupdates/util/PetLevelingTest.kt
Labels: bug-fix

#538 No more final changes
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ProfileViewer.java
Labels: bug-fix

#549 Really big Bazaar change
  src/main/java/io/github/moulberry/notenoughupdates/auction/APIManager.java
Labels: bug-fix

#556 Kuudra Party PV
  src/main/java/io/github/moulberry/notenoughupdates/listener/ChatListener.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Misc.java
Labels: feature

#543 Add tooltip resizing
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinGuiUtils.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/TooltipTweaks.java
  src/main/resources/mixins.notenoughupdates.json
Labels: feature

#557 Fix npe spam when rendering a player model in a recipe
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinLayerDeadmau5Head.java
  src/main/resources/mixins.notenoughupdates.json
Labels: bug-fix

#551 Fixed 2nd pet skull not rendering and breaking with custom gui scale
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/PetInfoOverlay.java
Labels: bug-fix

#528 Made it so barriers appear where you are unable to slot bind to
  src/main/java/io/github/moulberry/notenoughupdates/events/ReplaceItemEvent.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/SlotLocking.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinGuiContainer.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinInventoryPlayer.java
Labels: feature

#553 Added ability to multiply pet xp gain per pet
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/PetInfoOverlay.java
Labels: bug-fix

#559 Use a long for skils totalXP fixes #555
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/BasicPage.java
Labels: bug-fix

#561 Fixed Powder Checker
  src/main/java/io/github/moulberry/notenoughupdates/listener/ChatListener.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Mining.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/PowderGrindingOverlay.java
Labels: bug-fix

#565 UPDATE COPYRIGHT PROFILE
  .idea/copyright/NotEnoughUpdates.xml
Labels: documentation

#517 Want to Complete Commission Tasks Like a Pro? This Feature is a Must-Have
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Mining.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/MiningOverlay.java
Labels: feature

#558 Fix [NEU] API is down not showing
  src/main/java/io/github/moulberry/notenoughupdates/ItemPriceInformation.java
Labels: bug-fix

#563 Cancel wardrobe hotkey inputs
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/WardrobeMouseButtons.kt
Labels: bug-fix

#566 Do not always include essence profit in Croesus overlay
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/DungeonNpcProfitOverlay.java
Labels: bug-fix

#568 Recipe hotkeys in experimentation table.
  src/main/java/io/github/moulberry/notenoughupdates/recipes/CraftingOverlay.java
Labels: feature

#552 Fixed double register of view uses or recipes
  src/main/java/io/github/moulberry/notenoughupdates/NEUOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/GuiItemRecipe.java
Labels: bug-fix

#554 Annotation registering (and also some comptime performance)
  annotations/build.gradle.kts
  annotations/src/main/kotlin/io/github/moulberry/notenoughupdates/autosubscribe/NEUAutoSubscribe.kt
  annotations/src/main/kotlin/io/github/moulberry/notenoughupdates/autosubscribe/NEUAutoSymbolProcessor.kt
  annotations/src/main/kotlin/io/github/moulberry/notenoughupdates/autosubscribe/NEUAutoSymbolProcessorProvider.kt
  annotations/src/main/kotlin/io/github/moulberry/notenoughupdates/autosubscribe/NEUEventSubscriber.kt
  annotations/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
  build.gradle.kts
  buildSrc/src/main/kotlin/neubs/buildflags.kt
  gradle.properties
  oneconfigquarantine/build.gradle.kts
  settings.gradle.kts
  src/main/java/io/github/moulberry/notenoughupdates/NEUManager.java
  src/main/java/io/github/moulberry/notenoughupdates/NotEnoughUpdates.java
  src/main/java/io/github/moulberry/notenoughupdates/cosmetics/CapeManager.java
  src/main/java/io/github/moulberry/notenoughupdates/dungeons/DungeonMap.java
  src/main/java/io/github/moulberry/notenoughupdates/listener/OldAnimationChecker.java
  src/main/java/io/github/moulberry/notenoughupdates/loader/KotlinLoadingTweaker.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/AbiphoneContactHelper.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/AbiphoneFavourites.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/AbiphoneWarning.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/AntiCoopAdd.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/AuctionBINWarning.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/AuctionProfit.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/BetterContainers.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/CrystalOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/CrystalWishingCompassSolver.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/CustomItemEffects.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/DungeonNpcProfitOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/DwarvenMinesWaypoints.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/EnchantingSolvers.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/FairySouls.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/FishingHelper.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/ItemCooldowns.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/ItemCustomizeManager.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/MiningStuff.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/NullzeeSphere.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/PowerStoneStatsDisplay.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/SlotLocking.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/SunTzu.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/WardrobeMouseButtons.kt
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/WitherCloakChanger.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/customblockzones/CustomBiomes.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/customblockzones/DwarvenMinesTextures.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/item/enchants/EnchantStyleCustomizer.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/world/EnderNodeHighlighter.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/world/FrozenTreasuresHighlighter.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/world/GlowingMushroomHighlighter.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/CalendarOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/InventoryStorageSelector.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/SignCalculator.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/TrophyRewardOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/minionhelper/MinionHelperManager.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/EquipmentOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/FuelBar.java
  src/main/java/io/github/moulberry/notenoughupdates/util/Constants.java
  src/main/java/io/github/moulberry/notenoughupdates/util/SBInfo.java
  src/main/java/io/github/moulberry/notenoughupdates/util/TitleUtil.java
  src/main/java/io/github/moulberry/notenoughupdates/util/XPInformation.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/util/PetLeveling.kt
Labels: feature

#574 Fix NPE when resetting blur shader
  src/main/java/io/github/moulberry/notenoughupdates/core/BackgroundBlur.java
Labels: bug-fix

#573 Fixes NPE when minion has colour code in name
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/minionhelper/loaders/MinionHelperChatLoader.java
Labels: bug-fix

#572 Equipment overlay pet item crash fix
  src/main/java/io/github/moulberry/notenoughupdates/util/ItemUtils.java
Labels: bug-fix

#569 Fixed NPE in AuctionBINWarning
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/AuctionBINWarning.java
Labels: bug-fix

#567 Pelts and North Stars to Minion Helper price
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/minionhelper/render/MinionHelperOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/minionhelper/util/MinionHelperPriceCalculation.java
Labels: feature

#535 Add EnforcedConfigValues: Allow disabling options via the repo
  src/main/java/io/github/moulberry/notenoughupdates/commands/help/SettingsCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/core/config/gui/GuiOptionEditor.java
  src/main/java/io/github/moulberry/notenoughupdates/core/config/struct/ConfigProcessor.java
  src/main/java/io/github/moulberry/notenoughupdates/core/config/struct/GuiOptionEditorBlocked.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/miscfeatures/EnforcedConfigValues.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/util/Shimmy.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/util/kotlin/gson.kt
  src/main/resources/assets/notenoughupdates/textures/gui/config_blocked.png
Labels: feature

#562 Levels page in Profile Viewer
  Update Notes/2.1.1.md
  src/main/java/io/github/moulberry/notenoughupdates/commands/dev/DevTestCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/core/util/StringUtils.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/ProfileViewer.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/BasicPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/CollectionsPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/CrimsonIslePage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/DungeonPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ExtraPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/InventoriesPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/PlayerStats.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ProfileViewer.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/bestiary/BestiaryPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/LevelPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/CoreTaskLevel.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/DungeonTaskLevel.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/EssenceTaskLevel.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/MiscTaskLevel.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/SkillRelatedTaskLevel.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/SlayingTaskLevel.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/StoryTaskLevel.java
  src/main/java/io/github/moulberry/notenoughupdates/util/Constants.java
  src/main/java/io/github/moulberry/notenoughupdates/util/Utils.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/util/hypixelapi/Collection.kt
  src/main/resources/assets/notenoughupdates/pv_basic.png
  src/main/resources/assets/notenoughupdates/pv_levels.png
Labels: feature
