Repository NotEnoughUpdates/NotEnoughUpdates, pull requests merged in 2023-03, with the labels that each got.

#638 Fixed colour formatting on sb levels >= 360
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ProfileViewer.java
Labels: bug-fix

#637 2x Powder Event support for powder tracker
  src/main/java/io/github/moulberry/notenoughupdates/overlays/PowderGrindingOverlay.java
Labels: bug-fix

#649 Fix NPE in Level Page v4
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/MiscTaskLevel.java
Labels: bug-fix

#648 Fix /neudevtest useragent command
  src/main/kotlin/io/github/moulberry/notenoughupdates/commands/dev/DevTestCommand.kt
Labels: bug-fix

#624 Multiple tweaks to the Todo Overlay
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/MiscOverlays.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/OverlayManager.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/TimersOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/util/SBInfo.java
Labels: bug-fix, feature

#647 Fix champion showing -1 on combat overlay if you dont have it
  src/main/java/io/github/moulberry/notenoughupdates/overlays/CombatSkillOverlay.java
Labels: bug-fix

#609 Custom items in /neucustomize
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/ItemCustomizeManager.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/GuiItemCustomize.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinGuiContainer.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinGuiIngame.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinGuiIngameForge.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinItemRenderer.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinItemStack.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinLayerArmorBase.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinLayerCustomHead.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinRenderItem.java
  src/main/resources/mixins.notenoughupdates.json
Labels: feature

#623 Added prices in garden npcs
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/GardenNpcPrices.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/TooltipTweaks.java
Labels: feature

#635 Fixed builders ruler limit at 200 and tilling hoes showing blocks it wont till
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/CustomItemEffects.java
Labels: bug-fix

#652 Fixes NPE when exiting the Matriarch
  src/main/java/io/github/moulberry/notenoughupdates/overlays/TimersOverlay.java
Labels: bug-fix

#646 Dynamic Light Items
  src/main/java/io/github/moulberry/notenoughupdates/envcheck/NEUMixinConfigPlugin.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinOFDynamicLights.java
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/commands/misc/MiscCommands.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/miscgui/DynamicLightItemsEditor.kt
  src/main/resources/assets/notenoughupdates/disabled_button.png
  src/main/resources/assets/notenoughupdates/dynamic_light_items_editor.png
  src/main/resources/assets/notenoughupdates/enabled_button.png
  src/main/resources/mixins.notenoughupdates.json
Labels: feature

#522 cheapest museum item to donate
  src/main/java/io/github/moulberry/notenoughupdates/NotEnoughUpdates.java
  src/main/java/io/github/moulberry/notenoughupdates/listener/RenderListener.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/AbiphoneFavourites.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/AuctionProfit.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/DungeonNpcProfitOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/AccessoryBagOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/TrophyRewardOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/minionhelper/render/MinionHelperOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinRenderItem.java
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Misc.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Museum.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/EquipmentOverlay.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/events/ButtonExclusionZoneEvent.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/miscfeatures/inventory/MuseumCheapestItemOverlay.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/util/Rectangle.kt
  src/test/kotlin/io/github/moulberry/notenoughupdates/util/RectangleTest.kt
Labels: feature

#658 Added more warp icons
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/GuiInvButtonEditor.java
  src/main/resources/assets/notenoughupdates/invbuttons/presets.json
Labels: feature

#657 Fix mod thinking auction errored if the item is only on bin
  src/main/java/io/github/moulberry/notenoughupdates/ItemPriceInformation.java
Labels: bug-fix

#656 Added option to disable cit while in the storage overlay for fps
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/StorageManager.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/StorageOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinOptifineCustomItems.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/StorageGUI.java
  src/main/resources/mixins.notenoughupdates.json
Labels: feature

#650 Improve NPC shop generator
  build.gradle.kts
  src/main/java/io/github/moulberry/notenoughupdates/NEUManager.java
  src/main/java/io/github/moulberry/notenoughupdates/listener/RenderListener.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/Navigation.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/dev/RepoExporters.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/recipes/generators/ItemSearchGui.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/recipes/generators/ItemShopExporter.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/recipes/generators/RepoExporter.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/recipes/generators/RepoExporters.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/recipes/generators/RepoExportingContext.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/recipes/generators/RepoExportingInterruptedException.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/util/kotlin/Coroutines.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/util/kotlin/gson.kt
Labels: feature

#661 Fixed crash when item is set to ":" in /neurename
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/ItemCustomizeManager.java
Labels: bug-fix

#625 Made it so you can use per hour instead of per minute on crops and coins
  src/main/java/io/github/moulberry/notenoughupdates/dungeons/DungeonMap.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/SkillOverlays.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/FarmingSkillOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/util/SBInfo.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/util/SidebarUtil.kt
Labels: feature

#673 Fixed 3 Hotm Perk lores
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/MiningPage.java
Labels: bug-fix
