Repository NotEnoughUpdates/NotEnoughUpdates, pull requests merged in 2023-09, with the labels that each got.

#824 Fix Item Cooldown Inconsistency with Treecap
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/ItemCooldowns.java
Labels: bug-fix

#829 Added Starred Spirit Mask to the Item Cooldown Feature
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/ItemCooldowns.java
Labels: feature

#839 Fix repo download failing after sudden destruction of repo folder
  src/main/java/io/github/moulberry/notenoughupdates/NEUManager.java
Labels: bug-fix

#828 Fix skyblock level calculations in PV
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/SkyblockProfiles.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/bestiary/BestiaryData.kt
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/bestiary/BestiaryPage.kt
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/SlayingTaskLevel.java
Labels: bug-fix

#822 Fix museum overlay crash and bestiary page not refreshing on profile switch
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/bestiary/BestiaryPage.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/miscfeatures/inventory/MuseumCheapestItemOverlay.kt
Labels: bug-fix, crash

#821 Re-add join command
  src/main/kotlin/io/github/moulberry/notenoughupdates/commands/help/HelpCommand.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/commands/misc/JoinCommand.kt
Labels: feature

#820 Replace calculation with result in search bar on return press
  src/main/java/io/github/moulberry/notenoughupdates/NEUOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Toolbar.java
Labels: feature

#825 Default Armor Colour Feature
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/DefaultArmorColour.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinLayerArmorBase.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Misc.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/commands/dev/DevTestCommand.kt
Labels: feature
