Repository NotEnoughUpdates/NotEnoughUpdates, pull requests merged in 2023-06, with the labels that each got.

#711 Stop hardcoding npc prices
  src/main/java/io/github/moulberry/notenoughupdates/overlays/FarmingSkillOverlay.java
Labels: bug-fix

#712 Fixed Taxes in AH Overlay
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/AuctionProfit.java
Labels: bug-fix

#707 Fix navigation warps being broken by reading chat messages instead of…
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/Navigation.java
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/util/brigadier/dsl.kt
Labels: bug-fix

#703 NEUConfig: Add manadatory IQ test to api tab
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfigEditor.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/ApiData.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/miscfeatures/IQTest.kt
Labels: feature

#713 Made doubles great again
  src/main/java/io/github/moulberry/notenoughupdates/ItemPriceInformation.java
Labels: bug-fix

#718 Added new party hat sloth to item resolution query
  src/main/java/io/github/moulberry/notenoughupdates/util/ItemResolutionQuery.java
Labels: feature

#720 Added exact number values back to commissions
  src/main/java/io/github/moulberry/notenoughupdates/overlays/MiningOverlay.java
Labels: bug-fix

#721 Add variables to calculator
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/NeuSearchCalculator.java
  src/main/java/io/github/moulberry/notenoughupdates/util/Calculator.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/commands/misc/MiscCommands.kt
  src/test/java/io/github/moulberry/notenoughupdates/util/CalculatorTest.java
Labels: feature

#728 fix crash
  src/main/java/io/github/moulberry/notenoughupdates/listener/ItemTooltipRngListener.java
Labels: bug-fix

#733 Elaborate DCEVM instructions
  CONTRIBUTING.md
Labels: documentation

#724 Various rift related changes
  src/main/java/io/github/moulberry/notenoughupdates/NEUOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/entityviewer/EquipmentModifier.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/trophy/TrophyFishPage.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/recipes/generators/NPCLocationExporter.kt
Labels: feature

#727 Recent Pv profiles
  src/main/java/io/github/moulberry/notenoughupdates/listener/RenderListener.java
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ProfileViewer.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ProfileViewerUtils.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/SkyblockProfiles.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/commands/misc/ProfileViewerCommands.kt
  src/main/resources/assets/notenoughupdates/pv_elements.png
Labels: feature

#743 Fix pv NPE if no argument
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ProfileViewerUtils.java
Labels: bug-fix

#742 Fix cookie alert and sb menu thingy
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/CookieWarning.java
Labels: bug-fix

#746 fixing crash in neu calculator
  src/main/java/io/github/moulberry/notenoughupdates/util/Calculator.java
Labels: bug-fix

#745 fix bank balance and powder count in pv
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ExtraPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/MiningPage.java
Labels: bug-fix

#744 Changes that happened in alpha 17
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/TooltipTweaks.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/commands/misc/SetKeyCommand.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/miscfeatures/IQTest.kt
Labels: feature
