Repository NotEnoughUpdates/NotEnoughUpdates, pull requests merged in 2023-10, with the labels that each got.

#848 Add separate locked slots for rift and overworld.
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/SlotLocking.java
Labels: feature

#864 Hotkey to open ah/bz while hovering over an item
  src/main/java/io/github/moulberry/notenoughupdates/NEUOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/options/separatesections/Misc.java
Labels: feature

#869 Fix museum special pages
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/MuseumPage.java
Labels: bug-fix

#867 fix master mode comps not giving 2x collection for sb level page
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/SlayingTaskLevel.java
Labels: bug-fix

#871 Profile viewer fixes
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ExtraPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/MiningPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/MuseumPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/PetsPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/SkyblockProfiles.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/bestiary/BestiaryPage.kt
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/rift/RiftPage.java
Labels: bug-fix

#872 Add tuning stats to /pv
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/InventoriesPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/SkyblockProfiles.java
Labels: feature

#868 Add paginator to reforges in /hex overlay
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/hex/GuiCustomHex.java
Labels: bug-fix

#873 Fix auction house sort double rendering with chattriggers
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinGuiContainer.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinThreadDownloadImageDataThread.java
Labels: bug-fix

#878 Fixed TimersOverlay showing the wrong item
  src/main/java/io/github/moulberry/notenoughupdates/overlays/TimersOverlay.java
Labels: bug-fix

#880 Fix ah keybind with pets
  src/main/java/io/github/moulberry/notenoughupdates/NEUOverlay.java
Labels: bug-fix

#882 Add calculator precision option
  build.gradle.kts
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/NeuSearchCalculator.java
  src/main/java/io/github/moulberry/notenoughupdates/options/separatesections/Misc.java
  src/main/java/io/github/moulberry/notenoughupdates/util/Calculator.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/commands/misc/MiscCommands.kt
  src/test/kotlin/io/github/moulberry/notenoughupdates/util/BootstrapHook.kt
  src/test/kotlin/io/github/moulberry/notenoughupdates/util/CalculatorTest.kt
  src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
Labels: bug-fix, feature

#884 Pv bestiary
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/bestiary/BestiaryData.kt
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/bestiary/BestiaryPage.kt
  src/main/resources/assets/notenoughupdates/pv_bestiary_tab.png
Labels: feature

#887 Fix drop chance in mob loot
  src/main/java/io/github/moulberry/notenoughupdates/recipes/MobLootRecipe.java
Labels: bug-fix

#886 Fix enchanted books not working with bz keybind
  src/main/java/io/github/moulberry/notenoughupdates/NEUOverlay.java
Labels: bug-fix

#892 Fix chat symbols in click to pv
  src/main/java/io/github/moulberry/notenoughupdates/listener/ChatListener.java
Labels: bug-fix

#896 Update Luck of the Cave lore.
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/MiningPage.java
Labels: bug-fix

#902 Fixed Goblin Killer lore on the HotmPage
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/MiningPage.java
Labels: bug-fix

#890 Fix "+" not being added for pet replacements properly
  src/main/java/io/github/moulberry/notenoughupdates/NEUManager.java
Labels: bug-fix

#893 Add dungeon requirements to essence upgrade lore
  src/main/java/io/github/moulberry/notenoughupdates/recipes/EssenceUpgrades.java
Labels: feature

#908 Fixed Sky Mall perk lore on the PV Hotm Page
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/MiningPage.java
Labels: bug-fix

#906 Add rotating drops to mob loot.
  src/main/java/io/github/moulberry/notenoughupdates/recipes/MobLootRecipe.java
  src/main/java/io/github/moulberry/notenoughupdates/recipes/RecipeGenerator.java
Labels: feature

#911 Make Cake Timer in todo overlay reset when eating a refreshment cake
  src/main/java/io/github/moulberry/notenoughupdates/overlays/TimersOverlay.java
Labels: bug-fix
