Repository NotEnoughUpdates/NotEnoughUpdates, pull requests merged in 2023-02, with the labels that each got.

#570 Reactivate neu search bar.
  src/main/java/io/github/moulberry/notenoughupdates/NEUOverlay.java
Labels: bug-fix

#577 No bazaar data when no bazaar data
  src/main/java/io/github/moulberry/notenoughupdates/ItemPriceInformation.java
  src/main/java/io/github/moulberry/notenoughupdates/auction/APIManager.java
Labels: bug-fix

#514 Add support for all xp pets
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/PetInfoOverlay.java
Labels: bug-fix

#578 Restrict texture https upgrading to only minecraft.net
  src/main/java/io/github/moulberry/notenoughupdates/hooks/ThreadDownloadImageHook.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinThreadDownloadImageData.java
Labels: bug-fix

#579 Custom default font color in storage overlay
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/StorageOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/StorageGUI.java
Labels: feature

#582 Fixed NPE in CalendarOverlay
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/CalendarOverlay.java
Labels: bug-fix

#586 Align level in Basic PV page to center
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/BasicPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/DungeonTaskLevel.java
  src/main/java/io/github/moulberry/notenoughupdates/util/Utils.java
Labels: bug-fix

#589 Fix click in PV & Replace Texture
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/BasicPage.java
  src/main/resources/assets/notenoughupdates/pv_levels.png
Labels: bug-fix

#595 Fixed pickaxe cooldown not working on mining overlay when you have the durability bar disabled
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/ItemCooldowns.java
Labels: bug-fix

#587 Fixed Lags: Magical power in SkyBlock Menu
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/PowerStoneStatsDisplay.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ProfileViewer.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ProfileViewerUtils.java
  src/main/java/io/github/moulberry/notenoughupdates/util/ApiUtil.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/events/ProfileDataLoadedEvent.kt
Labels: bug-fix

#593 Fixed Major issue of sound playing when clicking on an invisible arrow
  src/main/java/io/github/moulberry/notenoughupdates/core/util/ArrowPagesUtils.java
Labels: bug-fix

#596 Fix Gui scale setting freaking out when your gui scale is set to 5x or higher
  src/main/java/io/github/moulberry/notenoughupdates/util/Utils.java
Labels: bug-fix

#597 Fix NPE in Level Page (v1)
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/EssenceTaskLevel.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/MiscTaskLevel.java
Labels: bug-fix

#590 ApiUtil: Add developer only user agent override
  src/main/java/io/github/moulberry/notenoughupdates/commands/dev/DevTestCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
  src/main/java/io/github/moulberry/notenoughupdates/util/ApiUtil.java
Labels: feature

#600 Fixed prerelease update notification and changed version
  src/main/java/io/github/moulberry/notenoughupdates/NotEnoughUpdates.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/updater/AutoUpdater.java
Labels: bug-fix

#583 Bingo has already enough to do.
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/MiscOverlays.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/TimersOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/util/SBInfo.java
Labels: feature

#571 Frozen treasure pet conflict fix
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/world/FrozenTreasuresHighlighter.java
Labels: bug-fix

#581 Fix Muscle Memory
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/CookieWarning.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Misc.java
  src/main/java/io/github/moulberry/notenoughupdates/util/SBInfo.java
  src/main/java/io/github/moulberry/notenoughupdates/util/Utils.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/miscfeatures/OldSkyBlockMenu.kt
Labels: feature

#607 Add event task & other things in Level Page
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/LevelPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/CoreTaskLevel.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/DungeonTaskLevel.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/EssenceTaskLevel.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/EventTaskLevel.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/MiscTaskLevel.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/SkillRelatedTaskLevel.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/SlayingTaskLevel.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/StoryTaskLevel.java
Labels: feature

#606 Revert nw location
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/BasicPage.java
Labels: bug-fix

#614 Changed the release thing from repo to normal
  README.md
Labels: documentation

#615 Workaround for NEUOverlay crash
  src/main/java/io/github/moulberry/notenoughupdates/NEUOverlay.java
Labels: bug-fix

#592 ApiUtil: Add cache with per request timeout and per class histogram
  src/main/java/io/github/moulberry/notenoughupdates/auction/APIManager.java
  src/main/java/io/github/moulberry/notenoughupdates/commands/dev/DevTestCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/commands/misc/PronounsCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/cosmetics/CapeManager.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/minionhelper/loaders/MinionHelperApiLoader.java
  src/main/java/io/github/moulberry/notenoughupdates/options/customtypes/NEUDebugFlag.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ProfileViewer.java
  src/main/java/io/github/moulberry/notenoughupdates/util/ApiUtil.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/util/ApiCache.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/util/MinecraftExecutor.kt
Labels: bug-fix

#576 Pet overlay progress hider, pet icon moved, and neudevtest value
  src/main/java/io/github/moulberry/notenoughupdates/commands/dev/DevTestCommand.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/PetInfoOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/PetOverlay.java
Labels: feature

#617 Fix NPE in Level Page (v2)
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/CoreTaskLevel.java
Labels: bug-fix

#618 Add option to mute composter
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/MutingComposter.java
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Garden.java
Labels: feature

#620 Fixed Calendar Buttons and special category some not existing tooltips
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/CalendarOverlay.java
Labels: bug-fix

#619 ApiCache: Fix apparent NullPointerException
  src/main/kotlin/io/github/moulberry/notenoughupdates/util/ApiCache.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/util/kotlin/completablefuture.kt
Labels: bug-fix

#611 HotmInformation rework
  src/main/java/io/github/moulberry/notenoughupdates/NEUManager.java
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
  src/main/java/io/github/moulberry/notenoughupdates/recipes/ForgeRecipe.java
  src/main/java/io/github/moulberry/notenoughupdates/util/HotmInformation.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/util/HotmInformation.kt
Labels: feature

#604 Added Sky Mall to Dwarven Overlay
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/CalendarOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Mining.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/MiningOverlay.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/guifeatures/SkyMallDisplay.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/util/SkyBlockTime.kt
  src/test/kotlin/io/github/moulberry/notenoughupdates/util/SkyBlockTimeTest.kt
Labels: feature

#601 Fixes messages not showing after beating a dungeon
  src/main/java/io/github/moulberry/notenoughupdates/dungeons/DungeonWin.java
Labels: bug-fix

#621 Museum: Display hydrated items for items taken outside of the repo
  Update Notes/2.1.1.md
  src/main/java/io/github/moulberry/notenoughupdates/NEUManager.java
  src/main/java/io/github/moulberry/notenoughupdates/events/GuiContainerBackgroundDrawnEvent.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinGuiContainer.java
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Museum.java
  src/main/java/io/github/moulberry/notenoughupdates/util/ItemResolutionQuery.java
  src/main/java/io/github/moulberry/notenoughupdates/util/LRUCache.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/miscfeatures/inventory/MuseumItemHighlighter.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/util/KotlinStringUtils.kt
  src/main/kotlin/io/github/moulberry/notenoughupdates/util/MuseumUtil.kt
Labels: feature

#626 Fix crashes in levels page
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/CoreTaskLevel.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/EventTaskLevel.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/MiscTaskLevel.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/level/task/SkillRelatedTaskLevel.java
Labels: bug-fix

#616 Garden overlays
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/CustomItemEffects.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/ItemOverlays.java
Labels: feature

#628 Added a warning when trying to delete a preset
  src/main/java/io/github/moulberry/notenoughupdates/listener/RenderListener.java
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/PresetWarning.java
  src/main/java/io/github/moulberry/notenoughupdates/mixins/MixinGuiContainer.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/Garden.java
Labels: feature

#588 Magical power in SkyBlock Menu icon again
  src/main/kotlin/io/github/moulberry/notenoughupdates/miscfeatures/OldSkyBlockMenu.kt
Labels: feature

#634 Fix NPE when swapping islands
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/MutingComposter.java
Labels: bug-fix
