Repository NotEnoughUpdates/NotEnoughUpdates, pull requests merged in 2023-07, with the labels that each got.

#755 fix MuseumTooltipManager NPE
  src/main/kotlin/io/github/moulberry/notenoughupdates/miscfeatures/inventory/MuseumTooltipManager.kt
Labels: crash

#754 Fix Magical Power calculation
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ProfileViewerUtils.java
Labels: bug-fix

#758 Fix calculator preop operations
  src/main/java/io/github/moulberry/notenoughupdates/util/Calculator.java
  src/test/java/io/github/moulberry/notenoughupdates/util/CalculatorTest.java
  src/test/kotlin/io/github/moulberry/notenoughupdates/util/CalculatorTest.kt
Labels: bug-fix

#767 Fix leveling info related crash
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/DungeonPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/MiningPage.java
  src/main/java/io/github/moulberry/notenoughupdates/util/XPInformation.java
Labels: crash

#768 Funny Rainbow Bar
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/DungeonPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
Labels: bug-fix

#769 Makes vamp slayer work properly with the rng meter tooltip thingy
  src/main/java/io/github/moulberry/notenoughupdates/listener/ItemTooltipRngListener.java
Labels: bug-fix

#766 Add free rift infusion to timer
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/CalendarOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/options/NEUConfig.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/MiscOverlays.java
  src/main/java/io/github/moulberry/notenoughupdates/overlays/TimersOverlay.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/commands/help/HelpCommand.kt
Labels: feature

#773 Museum page
  src/main/java/io/github/moulberry/notenoughupdates/NotEnoughUpdates.java
  src/main/java/io/github/moulberry/notenoughupdates/options/seperateSections/ProfileViewer.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/ExtraPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/MuseumPage.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/SkyblockProfiles.java
  src/main/java/io/github/moulberry/notenoughupdates/util/Constants.java
  src/main/java/io/github/moulberry/notenoughupdates/util/Utils.java
  src/main/resources/assets/notenoughupdates/pv_inventories.png
  src/main/resources/assets/notenoughupdates/pv_museum.png
Labels: feature
