Repository NotEnoughUpdates/NotEnoughUpdates, pull requests merged in 2024-01, with the labels that each got.

#987 Fix crash for old player profiles
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
Labels: bug-fix

#992 Fixed another rift page crash
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/rift/RiftPage.java
Labels: bug-fix

#993 Fixed tuningData crash on PV
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/SkyblockProfiles.java
Labels: bug-fix

#986 Fix bestiary migration check for newly created profiles
  src/main/kotlin/io/github/moulberry/notenoughupdates/miscfeatures/profileviewer/bestiary/BestiaryData.kt
Labels: bug-fix

#1001 Fixed HATCCESSORY -> HATCESSORY
  src/main/java/io/github/moulberry/notenoughupdates/NEUOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/AccessoryBagOverlay.java
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/PlayerStats.java
Labels: bug-fix

#1000 Fixed MinionHelper not loading slayers correctly
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/minionhelper/loaders/MinionHelperApiLoader.java
Labels: bug-fix

#1002 Empty pv search bar instead of displaying error
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
Labels: bug-fix

#1004 feat: Version_ID +1
  src/main/java/io/github/moulberry/notenoughupdates/NotEnoughUpdates.java
Labels: documentation

#1006 Fix Goblin Burrows typo for Goblin Slayer commission
  src/main/java/io/github/moulberry/notenoughupdates/overlays/MiningOverlay.java
Labels: bug-fix

#1005 Add Treasure Hoarder Puncher commission
  src/main/java/io/github/moulberry/notenoughupdates/overlays/MiningOverlay.java
Labels: bug-fix, feature

#1009 Fix RNG Meter Progress
  src/main/java/io/github/moulberry/notenoughupdates/listener/ItemTooltipRngListener.java
Labels: bug-fix

#1008 Hide OldSBMenu and PetOverlay while being in the rift
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/PetInfoOverlay.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/miscfeatures/OldSkyBlockMenu.kt
Labels: bug-fix, feature

#1007 fix: Profile Viewer showing a blank page instead of loading
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/GuiProfileViewer.java
Labels: bug-fix
