Repository NotEnoughUpdates/NotEnoughUpdates, pull requests merged in 2024-02, with the labels that each got.

#1013 Fix commission todo timer
  src/main/java/io/github/moulberry/notenoughupdates/overlays/TimersOverlay.java
Labels: bug-fix

#1018 Fix crash when parsing bestiary/trophy fish data
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/trophy/TrophyFishPage.java
  src/main/kotlin/io/github/moulberry/notenoughupdates/miscfeatures/profileviewer/bestiary/BestiaryData.kt
Labels: bug-fix

#1011 Added Ctrl-Click to open bazaar to the minion helper
  src/main/java/io/github/moulberry/notenoughupdates/auction/APIManager.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/minionhelper/Minion.java
  src/main/java/io/github/moulberry/notenoughupdates/miscgui/minionhelper/render/MinionHelperOverlayHover.java
Labels: feature

#1022 fix: Custom Todo edit page spelling mistake
  src/main/resources/assets/notenoughupdates/gui/customtodos/edit.xml
Labels: bug-fix

#1021 +1 Version
  src/main/java/io/github/moulberry/notenoughupdates/NotEnoughUpdates.java
Labels: documentation

#1028 fix: Incorrect powder costs in pv
  src/main/java/io/github/moulberry/notenoughupdates/profileviewer/MiningPage.java
Labels: bug-fix

#1019 Fix rare NPE in crystal hollow chest highlighter
  src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/world/CrystalHollowChestHighlighter.java
Labels: bug-fix
